name: slp_to_spr
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: seragud <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  slp_reader:
    path: ../slp_reader
  yamlicious: ^0.1.0

dev_dependencies:
  test: ^1.0.0
