name: pathing
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner:
  build_web_compilers:
