name: slp_reader
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: seragud <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  image:

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
